hinglish_to_english = {
    # Abusive / Negative words
    "chutiya": "idiot",
    "madarchod": "motherfucker",
    "bhosdike": "bastard",
    "harami": "bastard",
    "kutte": "dog",
    "bewakoof": "stupid",
    "bakwas": "nonsense",
    "faltu": "useless",
    "ghatiya": "cheap",
    "lanat": "disgrace",
    "gawar": "illiterate",
    "ullu": "fool",
    "chodu": "fucker",
    "kamine": "scoundrel",
    "nalayak": "incompetent",
    "bewkuf": "stupid",
    "jhantu": "jerk",
    "chakka": "coward",
    "bhosriwala": "bastard",
    "randi": "prostitute",
    "haraamkhor": "cheater",
    "kutti": "bitch",
    "chakkar": "affair",
    "ullu ka patha": "idiot",
    "chutiyapa": "nonsense",
    "chutiye": "idiots",
    "behenchod": "sisterfucker",
    "madarchod": "motherfucker",

    # Positive words
    "mast": "awesome",
    "bindaas": "cool",
    "badhiya": "good",
    "accha": "good",
    "acha": "good",
    "masttt": "amazing",
    "dilse": "wholeheartedly",
    "shandar": "amazing",
    "kamal": "wonderful",
    "zabardast": "great",
    "sahi": "right",
    "superb": "awesome",

    # Neutral / Common words
    "haan": "yes",
    "nahi": "no",
    "arey": "",
    "arre": "",
    "bhai": "brother",
    "bhaiya": "brother",
    "yaar": "friend",
    "abey": "",
    "abe": "",
    "kyu": "why",
    "kyun": "why",
    "ky": "why",
    "kaam": "work",
    "ghar": "home",
    "chalo": "let's go",
    "dekh": "see",
    "bolo": "speak",
    "kya": "what",
    "kaise": "how",
    "theek": "fine",
    "haanbhai": "yes brother",
    "maza": "fun",
    "thik": "fine",
    "suna": "heard"
}
